SQL> SELECT *
   FROM CUSTOMERS
   WHERE ID IN (SELECT ID
         FROM CUSTOMERS
         WHERE SALARY > 4500) ;

         UPDATE CUSTOMERS
            SET SALARY = SALARY * 0.25
            WHERE AGE IN (SELECT AGE FROM CUSTOMERS_BKP
               WHERE AGE >= 27 );
